apiVersion: v1
kind: Service
metadata:
  namespace: clusterchallenge
  name: worker1
  labels:
    app: worker1
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: worker1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: clusterchallenge
  name: worker1
  labels:
    app: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker1
  template:
    metadata:
      labels:
        app: worker1
    spec:
      containers:
      - name: worker1
        image: rickevry/cluster-challenge-worker1:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        env:
        - name: PROTOHOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ClusterSettings__PIDConnectionString
          value: "mongodb://admin:password@mongodb:27017/?authSource=admin"
        - name: CLusterSettings__PIDDatabaseName
          value: "ProtoMongo"
        - name: ClusterSettings__PIDCollectionName
          value: "PID"
        - name: ClusterSettings__ClusterPort
          value: "0"
        - name: ClusterSettings__ClusterHost
          value: "protohost"
