apiVersion: v1
kind: Service
metadata:
  namespace: clusterchallenge
  name: mongodb
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: clusterchallenge
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: mongodb
        image: mongo:4.4.3-bionic
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
      nodeSelector:
        kubernetes.io/hostname: aks-nodepool1-24781992-1
