apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: coreapi
  labels:
    app: coreapi
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 6102
    name: actors
  selector:
    app: coreapi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: coreapi
  labels:
    app: coreapi
spec:
  serviceName: coreapi
  replicas: 1
  selector:
    matchLabels:
      app: coreapi
  template:
    metadata:
      labels:
        app: coreapi
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: coreapi
        image: skfdevopsacr.azurecr.io/dam2.core.rest:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 6102
          protocol: TCP
        env:
        - name: PROTOHOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP