apiVersion: v1
kind: Service
metadata:
  namespace: damdev
  name: coreapi
  labels:
    app: coreapi
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: coreapi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: damdev
  name: coreapi
  labels:
    app: coreapi
spec:
  serviceName: coreapi
  replicas: 1
  selector:
    matchLabels:
      app: coreapi
  template:
    metadata:
      labels:
        app: coreapi
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: coreapi
        image: skfdevopsacr.azurecr.io/dam2.core.rest:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        env:
        - name: PROTOHOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ClusterSettings__PIDConnectionString
          value: "mongodb://admin:password@mongodb:27017/?authSource=admin"
        - name: CLusterSettings__PIDDatabaseName
          value: "ProtoId"
        - name: ClusterSettings__PIDCollectionName
          value: "ProtoId-Dev"
        - name: DatabaseSettings__CollectionName
          value: "DAM-Dev"
        - name: BlobContainerConfiguration__ContainerName
          value: "damassetsdev"
        - name: ClusterSettings__ClusterPort
          value: "0"          
        - name: ClusterSettings__ClusterHost
          value: "protohost"    